name: Deploying FastAPI Book API

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    if_merged:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps: 
        - name: Deploy to Render
          run: |
            curl -X POST "${{ secrets.RENDEY_DEPLOY_HOOK }}"


