name: Deploying FastAPI Book API

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps: 
      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-culc7vin91rc73ea35j0?key=vqis0i0eWyE"

      - name: Ensure Workflow Completes
        run: exit 0

