name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Render Deployment
        id: trigger_deployment
        run: |
          response=$(curl -X POST "https://api.render.com/v1/deploys/YOUR_SERVICE_ID" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json")
          echo "response=$response" >> $GITHUB_ENV
          echo "deployment_id=$(echo $response | jq -r '.id')" >> $GITHUB_ENV

      - name: Wait for Deployment to Complete
        run: |
          deployment_id=${{ env.deployment_id }}
          echo "Waiting for deployment $deployment_id to complete..."
          while true; do
            status_response=$(curl -X GET "https://api.render.com/v1/deployments/$deployment_id" \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
              -H "Content-Type: application/json")
            status=$(echo $status_response | jq -r '.status')
            echo "Current status: $status"
            if [[ "$status" == "succeeded" || "$status" == "failed" ]]; then
              echo "Deployment completed with status: $status"
              break
            fi
            sleep 10  # Wait for 10 seconds before checking again
          done
